# CI de Nível 02 - Execução automática agendada

name: 'Execução Agendada'

on:
  schedule:
    - cron: '0 22 * * 1'  # Executa às 19h BRT (22h UTC) toda segunda-feira
  # Se quiser manter push manual, adicione:
  # workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x  
      
      - name: Instalando o Yarn
        run: npm install -g yarn
      
      - name: Instalando as dependências do projeto
        run: yarn

      - name: Instalando o Playwright
        run: yarn playwright install

      - name: Executando os testes E2E
        run: yarn run e2e
