# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'papeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = 'workflow_dispatch'
# gatilho de execução agendada = 'schedule'
# gstilho de execução a partir de outro pipeline = 'workflow_run'


on:
  workflow_run:
    workflows: ['Execução Manual']  # Nome do workflow que deve ser concluído antes deste
    types:
      - completed  # Este workflow será acionado quando o workflow "Execução Automática" for concluído  

# jobs que serão executados
jobs:
  e2e-test:
    # definindo o ambiente onde o job será executado
    runs-on: ubuntu-latest

    # condicional para garantir que o job só execute se o workflow anterior foi bem-sucedido
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # passos do script de build
    steps:
      #clone do repositório
      - uses: actions/checkout@v4

      #instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x  
      
      #instalação do yarn
      - name: Instalando o Yarn
        run: npm install -g yarn
      
      #instalação das dependências do projeto
      - name: Instalando as dependências do projeto
        run: yarn

      #instalação do Playwright
      - name: Instalando o Playwright
        run: yarn playwright install

      #execução dos testes E2E
      - name: Executando os testes E2E
        run: yarn run e2e