# CI de Nível 04 - Disparo dos testes dentro do pipe de dev.

# nome do nosso 'papeline'
name: 'Execução Integrada'

on:
  workflow_dispatch


# jobs que serão executados
jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      # clone do repositório
      - uses: actions/checkout@v4
      
      # instalação do yarn
      - name: Instalando o Yarn
        run: npm install -g yarn
      
      # instalação das dependências do projeto
      - name: Instalando as dependências do projeto
        run: yarn

      # instalação do Playwright
      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest

    steps:
      # clone do repositório
      - uses: actions/checkout@v4
      
      # instalação do yarn
      - name: Instalando o Yarn
        run: npm install -g yarn
      
      # instalação das dependências do projeto
      - name: Instalando as dependências do projeto
        run: yarn

      # instalação do Playwright
      - name: Executando os testes unitários
        run: yarn test

  e2e-test:
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      #clone do repositório
      - uses: actions/checkout@v4

      #instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x  
      
      #instalação do yarn
      - name: Instalando o Yarn
        run: npm install -g yarn
      
      #instalação das dependências do projeto
      - name: Instalando as dependências do projeto
        run: yarn

      #instalação do Playwright
      - name: Instalando o Playwright
        run: yarn playwright install

      #execução dos testes E2E
      - name: Executando os testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Relatório de Testes E2E
          path: ./playwright-report/

  Deploy:
    runs-on: ubuntu-latest

    steps:
      #clone do repositório
      - name: Simulando o Deploy
        run: echo "Deploy realizado com sucesso!"